#!/usr/bin/env bash
# =============================================================================
# bootstrap.sh — ONE-TIME setup of Terraform remote state backend
#
# Run this ONCE before running `terraform init` in either infra-base or
# infra-lab. It creates:
#   - S3 bucket:       sqlinj-tfstate-<ACCOUNT_ID>   (versioned, encrypted)
#   - DynamoDB table:  sqlinj-tfstate-lock            (state locking)
#
# Security notes:
#   - Bucket versioning enables recovery from accidental state corruption
#   - AES-256 SSE is used here (lab); production should use SSE-KMS with a
#     customer-managed key and a key policy restricting access to specific roles
#   - Public access is blocked at all levels — state files can contain
#     sensitive values (DB passwords, private keys generated by Terraform)
#   - The bucket name includes the account ID to avoid global S3 name conflicts
#
# Prerequisites: AWS CLI configured with credentials that can create S3 + DynamoDB
# Usage: ./bootstrap.sh [--dry-run]
# =============================================================================

set -euo pipefail

DRY_RUN=false
if [[ "${1:-}" == "--dry-run" ]]; then
  DRY_RUN=true
  echo "→ DRY RUN mode — no AWS resources will be created"
fi

REGION="ap-southeast-2"
ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
BUCKET_NAME="sqlinj-tfstate-${ACCOUNT_ID}"
DYNAMODB_TABLE="sqlinj-tfstate-lock"

echo "→ AWS Account:    ${ACCOUNT_ID}"
echo "→ Region:         ${REGION}"
echo "→ State bucket:   ${BUCKET_NAME}"
echo "→ DynamoDB table: ${DYNAMODB_TABLE}"
echo ""

# Guard: fail early if bucket already exists (idempotency check)
if aws s3api head-bucket --bucket "${BUCKET_NAME}" 2>/dev/null; then
  echo "✓ S3 bucket already exists — skipping creation"
else
  echo "→ Creating S3 state bucket..."
  if [[ "${DRY_RUN}" == "false" ]]; then
    aws s3api create-bucket \
      --bucket "${BUCKET_NAME}" \
      --region "${REGION}" \
      --create-bucket-configuration LocationConstraint="${REGION}"

    # Versioning — critical: allows recovery if state is corrupted or deleted
    aws s3api put-bucket-versioning \
      --bucket "${BUCKET_NAME}" \
      --versioning-configuration Status=Enabled

    # SSE-AES256 — lab choice; production: use aws:kms with CMK
    # KMS gives you: key rotation, cross-account access control, CloudTrail
    # audit of every state file read. AES256 is transparent and cheaper.
    aws s3api put-bucket-encryption \
      --bucket "${BUCKET_NAME}" \
      --server-side-encryption-configuration '{
        "Rules": [{
          "ApplyServerSideEncryptionByDefault": {
            "SSEAlgorithm": "AES256"
          },
          "BucketKeyEnabled": true
        }]
      }'

    # Block all public access — non-negotiable for state buckets
    aws s3api put-public-access-block \
      --bucket "${BUCKET_NAME}" \
      --public-access-block-configuration \
        "BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true"

    # Enable access logging (production best practice — who accessed state when)
    # Omitted here to avoid creating a second logging bucket in the lab.
    # Production: create a separate sqlinj-tfstate-logs-ACCOUNT_ID bucket and
    # configure logging to it.

    echo "✓ S3 bucket created and hardened"
  fi
fi

# Guard: fail early if DynamoDB table already exists
if aws dynamodb describe-table --table-name "${DYNAMODB_TABLE}" --region "${REGION}" 2>/dev/null; then
  echo "✓ DynamoDB table already exists — skipping creation"
else
  echo "→ Creating DynamoDB lock table..."
  if [[ "${DRY_RUN}" == "false" ]]; then
    aws dynamodb create-table \
      --table-name "${DYNAMODB_TABLE}" \
      --attribute-definitions AttributeName=LockID,AttributeType=S \
      --key-schema AttributeName=LockID,KeyType=HASH \
      --billing-mode PAY_PER_REQUEST \
      --region "${REGION}" \
      --tags \
        Key=Environment,Value=lab \
        Key=Project,Value=sqlinj \
        Key=ManagedBy,Value=terraform \
        Key=Component,Value=infra-base

    # Wait for table to become ACTIVE before returning
    echo "→ Waiting for DynamoDB table to become ACTIVE..."
    aws dynamodb wait table-exists \
      --table-name "${DYNAMODB_TABLE}" \
      --region "${REGION}"
    echo "✓ DynamoDB table created"
  fi
fi

echo ""
echo "============================================================"
echo "  Bootstrap complete!"
echo "============================================================"
echo ""
echo "  Update backend.tf in BOTH infra-base/ and infra-lab/ with:"
echo ""
echo "    bucket         = \"${BUCKET_NAME}\""
echo "    region         = \"${REGION}\""
echo "    dynamodb_table = \"${DYNAMODB_TABLE}\""
echo ""
echo "  Then run:"
echo "    cd terraform/infra-base && terraform init"
echo "    cd terraform/infra-lab  && terraform init"
echo "============================================================"
