apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: sqlinj
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 8080  # nginx-unprivileged listens on 8080; ingress still references port 80
  type: ClusterIP
