apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sqlinj-ingress
  namespace: sqlinj
  annotations: {}
spec:
  ingressClassName: nginx
  rules:
    - host: sqlinj.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 5001
          - path: /graphql-insecure
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 5001
          - path: /graphql-secure
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 5001
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 5001
