apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name }}
  namespace: {{ .Release.Namespace }} # This SecretStore is namespaced to your app
  labels:
    {{- include "sqlinj-backend-chart.labels" . | nindent 6 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.awsRegion }}
      auth:
        jwt: # Assumes IRSA for the ServiceAccount defined below
          serviceAccountRef:
            name: {{ .Values.secretsIrsa.serviceAccountName }} # References the SA created by 00a-secrets-serviceaccount.yaml
            # namespace: {{ .Release.Namespace }} # Optional: If SA is in the same namespace as SecretStore, this can be omitted. Explicit is fine too.