apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name }}
  namespace: {{ .Release.Namespace }} # This SecretStore will be namespaced to your app
  labels:
    app.kubernetes.io/name: {{ include "sqlinj-backend-chart.name" . }}
    helm.sh/chart: {{ include "sqlinj-backend-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.awsRegion }}
      auth:
        jwt: # Assumes IRSA for the ESO controller
          serviceAccountRef:
            name: {{ .Values.secretStore.esoControllerServiceAccountName }}
            namespace: {{ .Values.secretStore.esoControllerServiceAccountNamespace }}