apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-db-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "sqlinj-backend-chart.name" . }}
    helm.sh/chart: {{ include "sqlinj-backend-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.secretStore.name }} # References the SecretStore created by this chart
    kind: SecretStore
  target:
    name: {{ .Values.awsSecrets.k8sDbSecretName }} # K8s secret to create
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DB_USER: "{{ .username }}" # Key in AWS SM
        DB_PASSWORD: "{{ .password }}" # Key in AWS SM
  dataFrom:
    - extract:
        key: {{ .Values.awsSecrets.dbSecretNameInSM }} # Name of your secret in AWS SM