{{- /* This ServiceAccount will be created in your application's namespace */}}
{{- /* and annotated with the IAM Role for accessing AWS Secrets Manager. */}}
{{- if .Values.secretsIrsa.createServiceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.secretsIrsa.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.secretsIrsa.iamRoleArn }}
  labels:
    {{- include "sqlinj-backend-chart.labels" . | nindent 6 }}
{{- end }}