apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-jwt-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "sqlinj-backend-chart.name" . }}
    helm.sh/chart: {{ include "sqlinj-backend-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.awsSecrets.k8sJwtSecretName }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        JWT_SECRET: "{{ .JWT_SECRET }}" # Assumes key in AWS SM is JWT_SECRET
  dataFrom:
    - extract:
        key: {{ .Values.awsSecrets.jwtSecretNameInSM }}