apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "sqlinj-backend-chart.name" . }}
    helm.sh/chart: {{ include "sqlinj-backend-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http # Name of the port in the Deployment's container spec
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "sqlinj-backend-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}