# =============================================================================
# versions.tf — Provider and Terraform version constraints
#
# Why pin versions?
#   - Terraform and provider releases can introduce breaking changes.
#     Pinning ensures your config behaves identically across team members,
#     CI, and the nightly CodeBuild destroy job.
#   - ~> 5.0 means "any 5.x release" — gets you patch updates (bug fixes,
#     new resources) but not major-version breaking changes.
#   - In production you would pin the exact provider version in a .terraform.lock.hcl
#     file (generated by terraform init) and commit that file to the repo.
# =============================================================================

terraform {
  required_version = ">= 1.7.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

# Default tags applied to every resource this provider creates.
# This is more reliable than manually tagging each resource — it's enforced
# at the provider level and cannot be forgotten on individual resources.
#
# Security/operational value:
#   Component="infra-base" distinguishes permanent resources from lab resources.
#   The Lambda cost-sweep can use AutoDestroy=false to skip these.
provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      Environment = "lab"
      Project     = "sqlinj"
      ManagedBy   = "terraform"
      Component   = "infra-base"
      AutoDestroy = "false"
    }
  }
}
